# Generated by Django 6.0.6 on 2026-06-21 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, help_text='Upload the bank/UPI QR code image', null=True, upload_to='support/')),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=50)),
                ('upi_id', models.CharField(blank=True, help_text='e.g. conference@upi', max_length=100)),
                ('additional_notes', models.TextField(blank=True, help_text='Any extra instructions for contributors')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Page Info',
                'verbose_name_plural': 'Support Page Info',
            },
        ),
    ]
